name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
    - xeus-python
    - ipympl
    - matplotlib
    - numpy==2.0
    - scipy
